apiVersion: v1
kind: Service
metadata:
    name: "pjkubo-c34e"
    labels:
        app: "pjkubo-c34e"
spec:
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: "pjkubo-c34e"
